FROM jboss/wildfly:9.0.1.Final

MAINTAINER Nukool Muangsoon (nukoolmuangsoon@gmail.com) 
LABEL Description="JBoss-Sample-app Build Container"

COPY standalone.xml /opt/jboss/wildfly/standalone/configuration/
COPY index.html /opt/jboss/wildfly/welcome-content/

